---
# Globally leave the desktop disabled, let it be enabled in host-vars
desktop: false
# Set Czech language for desktop
language: czech

# Enable firewall setup and startup
# This needs to be enabled in host-vars
firewall: true
safe_network: 192.168.88.0/24

# Allow installation of larger software packages
brave: false
datovka: false
discord: false
edge: false
horizon: false
chrome: false
chromium: false
intune: false
kodi: false
lutris: false
mega: false
onlyoffice: false
openconnect: false
rocketchat: false
signal: false
slack: false
spotify: false
steam: false
stremio: false
telegram: false
ungoogled_chromium: false
vagrant: false
virtualbox: false
vlc: false
vscode: false
wine: false
zoom: false

# Enable RDP server installation
rdp_server: false