- name: Stop and disable sysstat services
  ansible.builtin.systemd:
    name: "{{ service_item }}"
    state: stopped
    enabled: no
  loop:
    - sysstat
    - sysstat-collect
  loop_control:
    loop_var: service_item

- name: Remove sysstat package completely
  ansible.builtin.package:
    name: sysstat
    state: absent

- name: Clean up sysstat directories
  ansible.builtin.file:
    path: "{{ dir_item }}"
    state: absent
  loop:
    - /var/log/sysstat
    - /var/log.hdd/sysstat
  loop_control:
    loop_var: dir_item
