# defaults file for cloud_tools
---
age: false
ansible: false
argocd: false
awscli: false
azcli: false
buildx: false
cephadm: false
clairctl: false
helm: false
ksops: false
kubeadm: false
kubectl: false
kubectx: false
kubens: false
kustomize: false
k9s: false
longhornctl: false
noobaa: false
oc: false
ocmirror: false
ocpinstall: false
operatorsdk: false
oras: false
python: false
roxctl: false
saml2aws: false
skopeo: false
slu: false
sops: false
starship: false
terraform: false
trivy: false
vault: false
velero: false
yajsv: false


# only if you're sure what you're doing
k8s_version: "1.33"

# common variables
app_dir: "/usr/local/bin"
install_dir: "/home/{{ user_ansible }}/install"

# OCP Login Script
cluster_url: "https://api.example.com:6443"
ocp_username: "username"
ocp_login: false
